name: treeshape-scripts 
channels:
  - conda-forge
  - anaconda
dependencies:
  - tabulate
  - ete3
  - pandas
  - numpy
  - scipy
  - seaborn
  - matplotlib
  - scikit-learn
  - pip
  - pip:
    - treeshapy
   
